### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by k3davis** [MakotoAtsu/AspNetCore_Vite_Template#1]
Please consider updating the template to target `net6.0`. It would also be helpful if you mentioned TypeScript is included as part of the README or in the description of the extension in the Visual Studio marketplace.

**Comment by MakotoAtsu** [comment]
Thank you for the Suggestions, I will try to migrate later : ) 
Maybe end of this month, A little bit busy, lol.

**Comment by MakotoAtsu** [comment]
#2

**Comment by MakotoAtsu** [comment]
<html>
<body>
<ol dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px !important; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;">Support Vite2.x and Vite3.x</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Support Asp.Net Core 6 (Minimal API and Controllers)</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Support 9 templates -- both Vue and React (list below)</li></ol><hr style="box-sizing: content-box; height: 0.25em; overflow: hidden; margin: 24px 0px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; background-color: var(--color-border-default); border: 0px; padding: 0px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

  | Vue + TypeScript | Vue | React + TypeScript | React
-- | -- | -- | -- | --
Asp.Net Core MVC 5 | O | X | X | X
Net 6 Use Controllers | O | O | O | O
Net 6 + Minimal API | O | O | O | O


</body>
</html>
